@baseURl = http://localhost:8004

### Get List of Notification
{{baseURl}}/

### Create new notification
POST {{baseURl}}/
Content-Type: application/json

{
    "threadId" : "asdfklvaslkdfjas",
    "body" : "fsdaf",
}